# Generated by Django 5.2.12 on 2026-03-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change_management', '0007_set_parallel_approval_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeriskassessment',
            name='residual_risk',
            field=models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('critical', 'Critical')], max_length=20),
        ),
    ]
